#!/usr/bin/env node
/**
 * Rebuild resources_db.js from data/resources/*.json and regenerate the
 * derived registries in app.js (ALL_PHASES, STATIC_WEIGHTS).
 *
 * index.html is the authority for which subtasks exist and in what order.
 * data/resources/*.json supplies each subtask's body. If those two disagree
 * — a renamed title, a missing entry — this fails and writes nothing, because
 * a silent mismatch breaks the sidebar and the progress maths at once.
 *
 * Usage: node tools/build.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.dirname(__dirname);
const HTML = path.join(ROOT, 'index.html');
const DB = path.join(ROOT, 'resources_db.js');
const APP = path.join(ROOT, 'app.js');
const RES = path.join(ROOT, 'data', 'resources');
const WEIGHTS = path.join(ROOT, 'data', 'weights.json');

const pageOf = t => t.startsWith('p0-') ? 'phase0.html'
                  : t.startsWith('p1-') ? 'phase1.html'
                  : t.startsWith('p2-') ? 'phase2.html'
                  : t.startsWith('p3-') ? 'phase3.html' : 'phase4.html';
const phaseOf = t => 'p' + t.match(/^(?:p(\d))|^jax/)?.[1];

// ---- 1. read the task/subtask tree out of index.html ----
const htmlSrc = fs.readFileSync(HTML, 'utf8');
const decode = s => s.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
                     .replace(/&#39;/g, "'").replace(/&quot;/g, '"');
const order = [], tree = {};
const sectionRe = /<div class="day-section" id="sec-([a-z0-9-]+)">([\s\S]*?)(?=<div class="day-section"|<!-- |$)/g;
for (const m of htmlSrc.matchAll(sectionRe)) {
  order.push(m[1]);
  tree[m[1]] = [...m[2].matchAll(/<div class="task-item-title">([\s\S]*?)<\/div>/g)]
    .map(x => decode(x[1].replace(/\s+/g, ' ').trim()));
}

// ---- 2. gather generated entries ----
const gen = {};
for (const f of fs.readdirSync(RES).filter(f => f.endsWith('.json'))) {
  const j = JSON.parse(fs.readFileSync(path.join(RES, f), 'utf8'));
  for (const page of Object.keys(j))
    for (const task of Object.keys(j[page])) {
      gen[page] = gen[page] || {};
      gen[page][task] = Object.assign(gen[page][task] || {}, j[page][task]);
    }
}

// ---- 3. assemble in document order, failing on any drift ----
const out = {}, missing = [], extra = [];
for (const t of order) {
  if (!tree[t].length) continue;                 // milestones carry no subtasks
  const page = pageOf(t);
  out[page] = out[page] || {};
  out[page][t] = {};
  for (const sub of tree[t]) {
    const e = gen[page]?.[t]?.[sub];
    if (!e) { missing.push(`${page}::${t}::${sub}`); continue; }
    out[page][t][sub] = e;
  }
}
for (const page of Object.keys(gen))
  for (const task of Object.keys(gen[page]))
    for (const sub of Object.keys(gen[page][task]))
      if (!(tree[task] || []).includes(sub)) extra.push(`${page}::${task}::${sub}`);

if (missing.length || extra.length) {
  console.error('KEY MISMATCH between index.html and data/resources — nothing written.');
  if (missing.length) console.error('  in index.html but no resource entry:\n    ' + missing.join('\n    '));
  if (extra.length) console.error('  resource entry with no matching subtask title:\n    ' + extra.join('\n    '));
  process.exit(1);
}

fs.writeFileSync(DB, `/**
 * resources_db.js — GENERATED by tools/build.js. Do not edit by hand.
 * Source: data/resources/*.json  ·  Keys come from index.html subtask titles.
 * Keyed by: Page Name -> Section ID (checkbox data-id) -> Subtask Title
 */

window.RESOURCES_DB = ` + JSON.stringify(out, null, 2) + ';\n');

// ---- 4. regenerate app.js registries ----
const W = JSON.parse(fs.readFileSync(WEIGHTS, 'utf8'));
const phases = {};
for (const t of order) (phases[phaseOf(t)] = phases[phaseOf(t)] || []).push(t);

const allPhases = ['const ALL_PHASES = {'];
['p0', 'p1', 'p2', 'p3', 'p4'].forEach((ph, i, a) => {
  allPhases.push(`  ${ph}: {`);
  allPhases.push(`    page: '${pageOf(phases[ph][0])}',`);
  allPhases.push(`    tasks: [${phases[ph].map(t => `'${t}'`).join(', ')}]`);
  allPhases.push('  }' + (i < a.length - 1 ? ',' : ''));
});
allPhases.push('};');

const BUILD = /\b(implement|build|write|derive|train|construct|create|port|rewrite|reproduce|fit|profile|benchmark|verify|prove|measure|publish|submit|ship|instrument|harden)\b/i;
const PRACTICE = /\b(practice|solve|work through|run|configure|set up|experiment|debug|trace|compare|classify|annotate|refactor|test|audit|inspect)\b/i;
const weigh = s => BUILD.test(s) ? 3 : PRACTICE.test(s) ? 2 : 1;

const sw = ['const STATIC_WEIGHTS = {', '  phases: {',
            '    ' + Object.entries(W.phases).map(([k, v]) => `${k}: ${v}`).join(', '), '  },', '  tasks: {'];
for (const ph of ['p0', 'p1', 'p2', 'p3', 'p4'])
  sw.push(`    // Phase ${ph[1]}`,
          '    ' + phases[ph].map(t => `'${t}': ${W.tasks[t] ?? 10}`).join(', ') + ',');
sw[sw.length - 1] = sw[sw.length - 1].replace(/,$/, '');
sw.push('  },', '  subtasks: {');
for (const ph of ['p0', 'p1', 'p2', 'p3', 'p4'])
  for (const t of phases[ph]) {
    if (!tree[t].length) continue;
    const base = W.tasks[t] ?? 10;
    for (const sub of tree[t])
      sw.push(`    ${JSON.stringify(`${pageOf(t)}::${t}::${sub}`)}: ${Math.max(1, Math.round(base / tree[t].length))},`);
  }
sw[sw.length - 1] = sw[sw.length - 1].replace(/,$/, '');
sw.push('  },', '  steps: {');
const stepLines = [];
for (const page of Object.keys(out))
  for (const task of Object.keys(out[page]))
    for (const sub of Object.keys(out[page][task]))
      (out[page][task][sub].steps || []).forEach((s, i) =>
        stepLines.push(`    ${JSON.stringify(`${page}::${task}::${sub}::${i}`)}: ${weigh(s)}`));
sw.push(stepLines.join(',\n'), '  }', '};');

let app = fs.readFileSync(APP, 'utf8');
app = app.slice(0, app.indexOf('const ALL_PHASES = {')) + allPhases.join('\n') + '\n\n'
    + app.slice(app.indexOf('// Helper to find the page filename'));
app = app.slice(0, app.indexOf('const STATIC_WEIGHTS = {')) + sw.join('\n') + '\n\n'
    + app.slice(app.indexOf('const STORE_KEY'));
fs.writeFileSync(APP, app);

let links = 0, entries = 0;
for (const page of Object.keys(out))
  for (const task of Object.keys(out[page]))
    for (const sub of Object.keys(out[page][task])) {
      entries++;
      for (const c of ['courses', 'papers', 'lectures', 'docs', 'videos', 'podcasts'])
        links += (out[page][task][sub][c] || []).length;
    }
console.log(`built: ${entries} resource entries, ${links} links, ${stepLines.length} step weights`);
